### ISSUE TITLE
Ordering of parameters for triangular matrices

### ISSUE THREAD

**Issue by stevencarlislewalker** [stevencarlislewalker/lme4ord#15]
Should it be all diagonal followed by all off diagonal, or more like `lme4` (as it is now)?

**Comment by bbolker** [comment]
I don't think it matters as long as it's clear and there's a convenient method for sorting them out as necessary (e.g. in `lme4` it's via `lower==0`)

**Comment by stevencarlislewalker** [comment]
Closed with bd2f8082d1ef
